
package DBsetup;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;

/**
 *
 * @author clone-sniper
 */
public class connectDB {
    
        public static final String driver = "org.apache.derby.jdbc.EmbeddedDriver";
        public static final  String url = "jdbc:derby://localhost:1527/CRM;create=true;";
        public static final  String username = "app";
        public static final  String password = "app";
    
    
    public Connection getConnection() throws Exception
    {
        try
        {
        Class.forName(driver);
        
        Connection conn = DriverManager.getConnection(url,username,password);
        //System.out.println("Connected to CRM DB server");
        return conn;
        }
        catch(Exception e)
        {           
            System.out.println(e);
        }
        
        return null;
    }
    
    public void createTable() throws Exception
    {
        try
        {   
            Connection conn = getConnection();  
            DatabaseMetaData md = conn.getMetaData();
            ResultSet rs = md.getTables(null, null, "CUSTOMER", null);
            if(!rs.next())
            {
                conn.createStatement().execute("create table Customer(ID int NOT NULL  GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) primary key, name varchar(20), Email varchar(30),PhoneNumber varchar(12))");
                System.out.println("Customer Table Created");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }    
}
